apiVersion: v1
kind: Namespace
metadata:
  name: "vantiqtools"
  labels:
    name: "vantiqtools"
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-f
  namespace: "vantiqtools"
spec:
  containers:
  - name: alpine-f
    image: quay.io/fujitake/alpine-f:1.3
    stdin: true
    tty: true
