apiVersion: v1
kind: Namespace
metadata:
  name: "vantiqtools"
  labels:
    name: "vantiqtools"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: timestamp
  namespace: "tools"
spec:
  selector:
      matchLabels:
        app: timestamp # Label selector that determines which Pods belong to the DaemonSet
  template:
    metadata:
      labels:
        app: timestamp # Pod template's label selector
    spec:
      containers:
      - name: timestamp
        image: alpine
        command: ["/bin/ash", "-c", "--"]
        args: ["while true; do echo -n 'Date is '; date +%Y-%m-%dT%H:%M:%S.%3N; sleep 1; done;"]
